spring:

  datasource:
    username: postgres
    password: Babu@7700
    url: jdbc:postgresql://localhost:5432/microshop

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

server:
  port: 9002